
import fs from "fs";
import path from "path";
const ROOT=process.cwd(), DIST=path.join(ROOT,"dist");
fs.rmSync(DIST,{recursive:true,force:true}); fs.mkdirSync(DIST,{recursive:true});
const read=n=>JSON.parse(fs.readFileSync(path.join(ROOT,"content",n),"utf8"));
const site=read("site.json"), faculty=read("faculty.json"), history=read("history.json"), globalEvents=read("global-events.json"), clinical=read("clinical-heritage.json"), videos=read("videos.json");
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const nav=()=>`<nav class="nav"><div class="container navin"><a class="brand" href="/">ZSA INTERNATIONAL EDUCATION<small>${esc(site.tagline)}</small></a><div class="links"><a href="/about-zsa/">About ZSA</a><a href="/lineage/">Lineage</a><a href="/faculty/">Faculty</a><a href="/education/">Education</a><a href="/clinical-heritage/">Clinical</a><a href="/global-education/">Global</a><a href="/video-library/">Videos</a><a href="/contact/">Contact</a></div></div></nav>`;
const footer=()=>`<footer><div class="container"><strong>${esc(site.siteName)}</strong><p>${esc(site.tagline)}</p><div class="social"><a href="${site.social.instagram}">Instagram</a><a href="${site.social.facebook}">Facebook</a>${site.social.youtube?`<a href="${site.social.youtube}">YouTube</a>`:""}</div><p>© ${new Date().getFullYear()} ${esc(site.siteName)}</p></div></footer>`;
const page=(title,desc,body,rel="",schema=null)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${site.domain}/${rel}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><link rel="stylesheet" href="/assets/css/site.css">${schema?`<script type="application/ld+json">${JSON.stringify(schema)}</script>`:""}</head><body>${nav()}${body}${footer()}</body></html>`;
const write=(rel,html)=>{const d=path.join(DIST,rel);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,"index.html"),html)};

const home=`<header class="hero"><div class="container"><div class="eyebrow">International Education · Clinical Heritage · Global Training</div><h1>Zhu’s Scalp Acupuncture, carried forward through clinical lineage and global education.</h1><p class="lead">An international education platform led by Dr. Ru Shan Shy and Dr. Sheng Chun Chang, connecting the clinical heritage of Professor Ming Qing Zhu with systematic ZSA training, case-based learning and international professional exchange.</p><div class="actions"><a class="btn primary" href="/lineage/">Explore the Lineage</a><a class="btn" href="/education/">Education</a><a class="btn" href="/video-library/">Video Library</a></div><div class="badges"><span class="badge">Clinical Heritage</span><span class="badge">Systematic ZSA</span><span class="badge">Dao Yin</span><span class="badge">International Training</span></div></div></header>
<section class="section"><div class="container grid g2"><div><div class="eyebrow">Heritage</div><h2>From clinical origins to international education.</h2><p class="lead">The history of ZSA is documented through clinical practice, teaching records, formal lineage, academic exchange and professional education.</p><a class="btn" href="/lineage/">View Heritage Timeline</a></div><img class="hero-photo" src="/assets/images/history/origins-public-demonstration.jpg" alt="Early public clinical demonstration related to Zhu’s Scalp Acupuncture"></div></section>
<section class="section"><div class="container"><div class="eyebrow">Lineage</div><h2>Professor Ming Qing Zhu → Dr. Ru Shan Shy & Dr. Sheng Chun Chang</h2><div class="grid g2"><img class="hero-photo" src="/assets/images/faculty/zhu-shy-chang-formal.jpg" alt="Professor Ming Qing Zhu with Dr. Ru Shan Shy and Dr. Sheng Chun Chang"><div class="card"><h3>Clinical transmission, not isolated technique.</h3><p>ZSA is taught as a clinical system: assessment, treatment strategy, scalp zones, functional response, Dao Yin and continuous re-evaluation.</p><a class="btn primary" href="/faculty/">Meet the Faculty</a></div></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Global Education</div><h2>Teaching across regions, one educational framework.</h2><div class="grid g3">${globalEvents.slice(0,3).map(e=>`<article class="card"><img class="photo" src="${e.image}" alt="${esc(e.title)}"><div class="eyebrow">${esc(e.region)}</div><h3>${esc(e.title)}</h3><p>${esc(e.caption)}</p></article>`).join("")}</div><div class="actions"><a class="btn" href="/global-education/">Explore Global Education</a></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Clinical Education</div><h2>Practice-based learning at the center.</h2><div class="grid g3"><div class="card"><h3>Clinical First</h3><p>Assessment, treatment strategy and functional response guide technique selection.</p></div><div class="card"><h3>Systematic ZSA</h3><p>ZSA is presented as a coherent clinical framework rather than isolated scalp points.</p></div><div class="card"><h3>Dao Yin Integration</h3><p>Patient participation and guided functional activity are integrated into treatment and reassessment.</p></div></div></div></section>`;
write("",page(`${site.siteName} | Zhu’s Scalp Acupuncture`,"International Zhu’s Scalp Acupuncture education, clinical heritage and global training.",home,"",{"@context":"https://schema.org","@type":"EducationalOrganization","name":site.siteName,"url":site.domain}));

write("about-zsa",page("About Zhu’s Scalp Acupuncture | ZSA International Education","Introduction to Zhu’s Scalp Acupuncture and its educational framework.",`<main class="section"><div class="container"><div class="eyebrow">About ZSA</div><h1>What is Zhu’s Scalp Acupuncture?</h1><p class="lead">This page will present a carefully sourced explanation of ZSA origins, clinical principles, treatment framework, Dao Yin and educational terminology.</p><div class="notice">Editorial standard: distinguish documented history, instructor interpretation and clinical observation.</div></div></main>`,"about-zsa/"));

write("lineage",page("ZSA Heritage & Lineage | ZSA International Education","Documented clinical heritage and educational transmission of Zhu’s Scalp Acupuncture.",`<main class="section"><div class="container"><div class="eyebrow">Heritage & Lineage</div><h1>A documented clinical tradition.</h1><p class="lead">Historical evidence, clinical practice, formal transmission, academic exchange and contemporary international education.</p><div class="grid g2">${history.map(h=>`<article class="card"><img class="photo" src="${h.image}" alt="${esc(h.title)}"><div class="eyebrow">${esc(h.category)} · ${esc(h.year)}</div><h3>${esc(h.title)}</h3><p class="muted">${esc(h.location)}</p><p>${esc(h.caption)}</p></article>`).join("")}</div></div></main>`,"lineage/"));

write("faculty",page("Faculty | ZSA International Education","Dr. Ru Shan Shy and Dr. Sheng Chun Chang.",`<main class="section"><div class="container"><div class="eyebrow">Faculty</div><h1>Dr. Ru Shan Shy & Dr. Sheng Chun Chang</h1><div class="grid g2">${faculty.map(f=>`<article class="card"><img class="photo" src="${f.photo}" alt="${esc(f.name)}"><h3>${esc(f.name)}</h3><p>${esc(f.headline)}</p><a class="btn" href="/faculty/${f.slug}/">Profile</a></article>`).join("")}</div></div></main>`,"faculty/"));
for(const f of faculty){write(`faculty/${f.slug}`,page(`${f.name} | ZSA International Education`,f.headline,`<main class="section"><div class="container"><div class="eyebrow">Faculty Profile</div><h1>${esc(f.name)}</h1><div class="grid g2"><div><p class="lead">${esc(f.headline)}</p><p>${esc(f.bio)}</p></div><img class="hero-photo" src="${f.photo}" alt="${esc(f.name)}"></div></div></main>`,`faculty/${f.slug}/`,{"@context":"https://schema.org","@type":"Person","name":f.name,"url":`${site.domain}/faculty/${f.slug}/`}))}

write("education",page("Education | ZSA International Education","Systematic professional education in Zhu’s Scalp Acupuncture.",`<main class="section"><div class="container"><div class="eyebrow">Education</div><h1>Foundations → Advanced → Clinical Integration</h1><div class="grid g3"><div class="card"><h3>Foundation</h3><p>Core ZSA framework, safety, assessment and treatment strategy.</p></div><div class="card"><h3>Advanced</h3><p>Complex presentations, refinement of clinical reasoning and functional reassessment.</p></div><div class="card"><h3>Clinical Masterclass</h3><p>Case-led teaching, demonstrations and supervised clinical reasoning.</p></div></div></div></main>`,"education/"));

write("clinical-heritage",page("Clinical Heritage | ZSA International Education","Practice-based clinical heritage and hospital learning in Zhu’s Scalp Acupuncture.",`<main class="section"><div class="container"><div class="eyebrow">Clinical Heritage</div><h1>Clinical learning at the bedside.</h1><p class="lead">Bedside observation, case discussion and supervised clinical learning form an important part of the historical educational record.</p><div class="notice">Patient-related images should only be published where consent and institutional requirements are satisfied.</div><div class="grid g3" style="margin-top:22px">${clinical.map(e=>`<article class="card"><img class="photo" src="${e.image}" alt="${esc(e.title)}"><h3>${esc(e.title)}</h3><p>${esc(e.caption)}</p></article>`).join("")}</div></div></main>`,"clinical-heritage/"));

write("global-education",page("Global Education | ZSA International Education","International Zhu’s Scalp Acupuncture teaching and academic exchange.",`<main class="section"><div class="container"><div class="eyebrow">Global Education</div><h1>One clinical framework, taught internationally.</h1><div class="grid g2">${globalEvents.map(e=>`<article class="card"><img class="photo" src="${e.image}" alt="${esc(e.title)}"><div class="eyebrow">${esc(e.region)}</div><h3>${esc(e.title)}</h3><p>${esc(e.caption)}</p></article>`).join("")}</div></div></main>`,"global-education/"));

write("video-library",page("Video Library | ZSA International Education","YouTube-based ZSA clinical and teaching video library.",`<main class="section"><div class="container"><div class="eyebrow">Video Library</div><h1>YouTube for delivery. ZSATW.com for clinical context and search.</h1><p class="lead">YouTube will be connected when the official channel is provided. Important videos will receive their own indexed educational pages.</p>${videos.map(v=>`<div class="card"><h3>${esc(v.title)}</h3><p>${esc(v.summary)}</p></div>`).join("")}</div></main>`,"video-library/"));

write("contact",page("Contact | ZSA International Education","Contact ZSA International Education.",`<main class="section"><div class="container"><div class="eyebrow">Contact</div><h1>Education & professional collaboration.</h1><div class="grid g2"><div class="card"><h3>Official Channels</h3><div class="social"><a href="${site.social.instagram}">Instagram</a><a href="${site.social.facebook}">Facebook</a></div></div><div class="card"><h3>Email</h3><p>${esc(site.contactEmail)}</p></div></div></div></main>`,"contact/"));

fs.cpSync(path.join(ROOT,"public"),DIST,{recursive:true});
const urls=["","about-zsa/","lineage/","faculty/","faculty/ru-shan-shy/","faculty/sheng-chun-chang/","education/","clinical-heritage/","global-education/","video-library/","contact/"];
fs.writeFileSync(path.join(DIST,"robots.txt"),`User-agent: *\nAllow: /\n\nSitemap: ${site.domain}/sitemap.xml\n`);
fs.writeFileSync(path.join(DIST,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${site.domain}/${u}</loc></url>`).join("")}</urlset>`);
console.log(`Built ${urls.length} pages into dist/`);
