
import fs from "fs";
import path from "path";
const ROOT=process.cwd(), DIST=path.join(ROOT,"dist");
fs.rmSync(DIST,{recursive:true,force:true}); fs.mkdirSync(DIST,{recursive:true});
const read=n=>JSON.parse(fs.readFileSync(path.join(ROOT,"content",n),"utf8"));
const site=read("site.json"), faculty=read("faculty.json"), history=read("history.json"), globalEvents=read("global-events.json"), clinical=read("clinical-heritage.json"), videos=read("videos.json"), regions=read("regions.json");
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const nav=()=>`<nav class="nav"><div class="container navin"><a class="brand" href="/">ZSA INTERNATIONAL EDUCATION<small>${esc(site.tagline)}</small></a><div class="links"><a href="/about-zsa/">About ZSA</a><a href="/lineage/">Lineage</a><a href="/faculty/">Faculty</a><a href="/education/">Education</a><a href="/clinical-heritage/">Clinical</a><a href="/global-education/">Global</a><a href="/video-library/">Videos</a><a href="/contact/">Contact</a></div></div></nav>`;
const footer=()=>`<footer><div class="container footer-grid"><div><strong>${esc(site.siteName)}</strong><p>${esc(site.tagline)}</p></div><div><strong>Explore</strong><p><a href="/about-zsa/">About ZSA</a><br><a href="/lineage/">Heritage & Lineage</a><br><a href="/global-education/">Global Education</a></p></div><div><strong>Connect</strong><p><a href="${site.social.instagram}">Instagram</a><br><a href="${site.social.facebook}">Facebook</a>${site.social.youtube?`<br><a href="${site.social.youtube}">YouTube</a>`:""}</p></div></div><div class="container small" style="margin-top:28px">© ${new Date().getFullYear()} ${esc(site.siteName)}</div></footer>`;
const page=(title,desc,body,rel="",schema=null)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${site.domain}/${rel}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${site.domain}/${rel}"><link rel="stylesheet" href="/assets/css/site.css">${schema?`<script type="application/ld+json">${JSON.stringify(schema)}</script>`:""}</head><body>${nav()}${body}${footer()}</body></html>`;
const write=(rel,html)=>{const d=path.join(DIST,rel);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,"index.html"),html)};

const home=`<header class="hero"><div class="container"><div class="eyebrow">Zhu’s Scalp Acupuncture · International Education</div><h1>Clinical heritage. Systematic ZSA. Global training.</h1><p class="lead">Dr. Ru Shan Shy and Dr. Sheng Chun Chang continue the clinical and educational transmission of Zhu’s Scalp Acupuncture through case-based teaching, systematic clinical reasoning and international professional education.</p><div class="actions"><a class="btn primary" href="/lineage/">Explore the Lineage</a><a class="btn" href="/about-zsa/">What is ZSA?</a><a class="btn" href="/global-education/">Global Education</a></div></div></header>
<section class="section"><div class="container grid g2"><div><div class="eyebrow">The Clinical Lineage</div><h2>Professor Ming Qing Zhu → Dr. Ru Shan Shy & Dr. Sheng Chun Chang</h2><p class="lead">The connection is documented through direct learning, clinical practice, formal transmission, teaching records and continuing international education.</p><a class="btn primary" href="/lineage/">View documented history</a></div><img class="hero-photo" src="/assets/images/faculty/zhu-shy-chang-formal.jpg" alt="Professor Ming Qing Zhu with Dr. Ru Shan Shy and Dr. Sheng Chun Chang"></div></section>
<section class="section"><div class="container"><div class="eyebrow">Clinical Framework</div><h2>A clinical system, not isolated scalp points.</h2><div class="grid g4"><div class="card"><div class="num">01</div><h3>Assessment</h3><p>Define the functional clinical problem before treatment.</p></div><div class="card"><div class="num">02</div><h3>Systematic ZSA</h3><p>Use treatment zones within a complete clinical strategy.</p></div><div class="card"><div class="num">03</div><h3>Reassessment</h3><p>Observe response and refine strategy during treatment.</p></div><div class="card"><div class="num">04</div><h3>Dao Yin</h3><p>Integrate active participation and guided functional activity.</p></div></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">International Education</div><h2>Regional teaching and professional exchange.</h2><div class="grid g2">${regions.map(r=>`<article class="card image-card"><img class="photo" src="${r.image}" alt="${esc(r.name)}"><div class="eyebrow">${esc(r.status)}</div><h3>${esc(r.name)}</h3><p>${esc(r.summary)}</p><a class="btn" href="/global-education/${r.slug}/">Explore ${esc(r.name)}</a></article>`).join("")}</div></div></section>`;
write("",page(`${site.siteName} | Zhu’s Scalp Acupuncture`,"International Zhu’s Scalp Acupuncture education, clinical heritage and global professional training.",home,"",{"@context":"https://schema.org","@type":"EducationalOrganization","name":site.siteName,"url":site.domain,"sameAs":[site.social.instagram,site.social.facebook].filter(Boolean)}));

write("about-zsa",page("About Zhu’s Scalp Acupuncture | ZSA International Education","Introduction to Zhu’s Scalp Acupuncture as a structured clinical system.",`<main><section class="page-hero"><div class="container"><div class="eyebrow">About Zhu’s Scalp Acupuncture</div><h1>A clinical system, not a collection of scalp points.</h1><p class="lead">ZSA is presented here as a structured clinical approach developed by Professor Ming Qing Zhu, emphasizing assessment, treatment strategy, immediate functional reassessment and Dao Yin.</p></div></section><section class="section"><div class="container"><div class="grid g2"><div class="card"><div class="num">01</div><h3>Assessment before needling</h3><p>Begin with the functional presentation and define what can be reassessed.</p></div><div class="card"><div class="num">02</div><h3>Treatment zones within a system</h3><p>Location and technique are linked to the clinical problem rather than memorized in isolation.</p></div><div class="card"><div class="num">03</div><h3>Immediate reassessment</h3><p>Clinical response is repeatedly observed during treatment.</p></div><div class="card"><div class="num">04</div><h3>Dao Yin</h3><p>Guided movement and active participation are integrated with needling and reassessment.</p></div></div></div></section></main>`,"about-zsa/"));

write("lineage",page("ZSA Heritage & Lineage | ZSA International Education","Documented clinical heritage and educational transmission of Zhu’s Scalp Acupuncture.",`<main><section class="page-hero"><div class="container"><div class="eyebrow">ZSA Heritage & Lineage</div><h1>Clinical heritage documented through learning, practice and teaching.</h1><p class="lead">Historical photographs, formal transmission, clinical learning, professional education and international exchange form the documentary basis of this archive.</p></div></section><section class="section"><div class="container"><div class="timeline-grid">${history.map(h=>`<article class="timeline-card"><img src="${h.image}" alt="${esc(h.title)}"><div class="timeline-meta">${esc(h.category)} · ${esc(h.year)}</div><h3>${esc(h.title)}</h3><p class="muted">${esc(h.location)}</p><p>${esc(h.caption)}</p></article>`).join("")}</div></div></section></main>`,"lineage/"));

write("faculty",page("Faculty | ZSA International Education","Dr. Ru Shan Shy and Dr. Sheng Chun Chang, international ZSA educators.",`<main><section class="page-hero"><div class="container"><div class="eyebrow">Faculty</div><h1>Dr. Ru Shan Shy & Dr. Sheng Chun Chang</h1><p class="lead">Clinical educators continuing the transmission of Zhu’s Scalp Acupuncture through systematic teaching and international professional education.</p></div></section><section class="section"><div class="container"><div class="grid g2">${faculty.map(f=>`<article class="card image-card"><img class="photo" src="${f.photo}" alt="${esc(f.name)}"><h2>${esc(f.name)}</h2><p>${esc(f.headline)}</p><a class="btn primary" href="/faculty/${f.slug}/">View profile</a></article>`).join("")}</div></div></section></main>`,"faculty/"));

for(const f of faculty){
const tags=f.focus.map(x=>`<span class="tag">${esc(x)}</span>`).join("");
const timeline=f.timeline.map(t=>`<div class="profile-row"><div class="profile-label">${esc(t.label)}</div><p>${esc(t.text)}</p></div>`).join("");
write(`faculty/${f.slug}`,page(`${f.name} | ZSA International Education`,f.headline,`<main><section class="page-hero"><div class="container"><div class="eyebrow">Faculty Profile</div><h1>${esc(f.name)}</h1><p class="lead">${esc(f.summary)}</p><div class="tag-row">${tags}</div></div></section><section class="section"><div class="container grid g2"><div><div class="eyebrow">Biography</div><h2>Clinical education grounded in lineage and multidisciplinary training.</h2><p class="profile-text">${esc(f.bio)}</p></div><img class="hero-photo" src="${f.photo}" alt="${esc(f.name)}"></div></section><section class="section"><div class="container"><div class="eyebrow">Professional Profile</div><div class="profile-table">${timeline}</div></div></section><section class="section"><div class="container"><a class="btn primary" href="/global-education/">Explore International Teaching</a></div></section></main>`,`faculty/${f.slug}/`,{"@context":"https://schema.org","@type":"Person","name":f.name,"url":`${site.domain}/faculty/${f.slug}/`,"affiliation":{"@type":"EducationalOrganization","name":site.siteName}}));
}

write("education",page("Education | ZSA International Education","Systematic professional education in Zhu’s Scalp Acupuncture.",`<main><section class="page-hero"><div class="container"><div class="eyebrow">Education</div><h1>From foundations to clinical integration.</h1><p class="lead">A progressive curriculum built around clinical reasoning, systematic ZSA technique, reassessment and Dao Yin.</p></div></section><section class="section"><div class="container"><div class="grid g3"><div class="card"><h3>Foundation</h3><p>Core framework, safety, assessment and treatment strategy.</p></div><div class="card"><h3>Advanced</h3><p>Complex presentations, refinement of strategy and functional reassessment.</p></div><div class="card"><h3>Clinical Masterclass</h3><p>Case-led teaching, demonstrations and supervised reasoning.</p></div></div></div></section></main>`,"education/"));

write("clinical-heritage",page("Clinical Heritage | ZSA International Education","Practice-based clinical heritage and hospital learning in ZSA.",`<main><section class="page-hero"><div class="container"><div class="eyebrow">Clinical Heritage</div><h1>Clinical learning at the bedside.</h1><p class="lead">Hospital-based observation, case discussion and supervised practice form an important part of the historical educational record.</p></div></section><section class="section"><div class="container"><div class="notice">Patient-related images should only be published where consent and institutional requirements are satisfied.</div><div class="grid g3" style="margin-top:24px">${clinical.map(e=>`<article class="card image-card"><img class="photo" src="${e.image}" alt="${esc(e.title)}"><h3>${esc(e.title)}</h3><p>${esc(e.caption)}</p></article>`).join("")}</div></div></section></main>`,"clinical-heritage/"));

write("global-education",page("Global Education | ZSA International Education","International ZSA teaching and professional academic exchange.",`<main><section class="page-hero"><div class="container"><div class="eyebrow">Global Education</div><h1>One clinical framework, taught internationally.</h1><p class="lead">Courses, intensive trainings and academic exchange documented as part of a durable international educational archive.</p></div></section><section class="section"><div class="container"><div class="grid g2">${regions.map(r=>`<article class="card image-card"><img class="photo" src="${r.image}" alt="${esc(r.name)}"><div class="eyebrow">${esc(r.status)}</div><h3>${esc(r.name)}</h3><p>${esc(r.summary)}</p><a class="btn" href="/global-education/${r.slug}/">Explore ${esc(r.name)}</a></article>`).join("")}</div></div></section></main>`,"global-education/"));

for(const r of regions){
write(`global-education/${r.slug}`,page(`${r.name} | ZSA Global Education`,r.headline,`<main><section class="page-hero"><div class="container"><div class="eyebrow">Global Education · ${esc(r.name)}</div><h1>${esc(r.headline)}</h1><p class="lead">${esc(r.summary)}</p></div></section><section class="section"><div class="container grid g2"><img class="hero-photo" src="${r.image}" alt="${esc(r.name)} ZSA education"><div><div class="eyebrow">${esc(r.status)}</div><h2>Regional focus</h2><ul class="feature-list">${r.highlights.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><p class="muted">Dates, cities, organizers and course archives will be added only from verified records.</p></div></div></section></main>`,`global-education/${r.slug}/`));
}

write("video-library",page("Video Library | ZSA International Education","YouTube-based ZSA clinical and teaching video library.",`<main><section class="page-hero"><div class="container"><div class="eyebrow">Video Knowledge Hub</div><h1>YouTube for delivery. ZSATW.com for clinical context and search.</h1><p class="lead">Important lectures and cases will receive dedicated pages with summaries, learning points, transcript context and structured video metadata.</p></div></section><section class="section"><div class="container">${videos.map(v=>`<div class="card"><h3>${esc(v.title)}</h3><p>${esc(v.summary)}</p></div>`).join("")}</div></section></main>`,"video-library/"));

write("contact",page("Contact | ZSA International Education","Contact ZSA International Education.",`<main><section class="page-hero"><div class="container"><div class="eyebrow">Contact</div><h1>Education & professional collaboration.</h1></div></section><section class="section"><div class="container grid g2"><div class="card"><h3>Official Channels</h3><p><a href="${site.social.instagram}">Instagram</a><br><a href="${site.social.facebook}">Facebook</a>${site.social.youtube?`<br><a href="${site.social.youtube}">YouTube</a>`:""}</p></div><div class="card"><h3>Email</h3><p>${esc(site.contactEmail)}</p></div></div></section></main>`,"contact/"));

fs.cpSync(path.join(ROOT,"public"),DIST,{recursive:true});
const urls=["","about-zsa/","lineage/","faculty/","faculty/ru-shan-shy/","faculty/sheng-chun-chang/","education/","clinical-heritage/","global-education/","global-education/australia/","global-education/asia/","global-education/europe/","global-education/north-america/","video-library/","contact/"];
fs.writeFileSync(path.join(DIST,"robots.txt"),`User-agent: *\nAllow: /\n\nSitemap: ${site.domain}/sitemap.xml\n`);
fs.writeFileSync(path.join(DIST,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${site.domain}/${u}</loc></url>`).join("")}</urlset>`);
console.log(`Built ${urls.length} pages into dist/`);
