
import fs from "fs"; import path from "path";
const ROOT=process.cwd(), DIST=path.join(ROOT,"dist");
fs.rmSync(DIST,{recursive:true,force:true}); fs.mkdirSync(DIST,{recursive:true});
const read=n=>JSON.parse(fs.readFileSync(path.join(ROOT,"content",n),"utf8"));
const site=read("site.json"), faculty=read("faculty.json"), history=read("history.json"),
globalEvents=read("global-events.json"), clinical=read("clinical-heritage.json"), videos=read("videos.json"),
regions=read("regions.json"), knowledge=read("knowledge.json"), zhu=read("professor-zhu.json");
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const nav=()=>`<nav class="nav"><div class="container navin"><a class="brand" href="/">ZSA <span>International Education</span></a><div class="links"><a href="/about-zsa/">About ZSA</a><a href="/lineage/">Lineage</a><a href="/faculty/">Faculty</a><a href="/education/">Education</a><a href="/knowledge/">Knowledge</a><a href="/global-education/">Global</a><a href="/video-library/">Videos</a><a href="/contact/">Contact</a></div></div></nav>`;
const footer=()=>`<footer><div class="container footer-grid"><div><strong>${esc(site.siteName)}</strong><p>${esc(site.tagline)}</p></div><div><strong>Education</strong><p><a href="/about-zsa/">About ZSA</a><br><a href="/knowledge/">Knowledge Hub</a><br><a href="/global-education/">Global Education</a></p></div><div><strong>Official channels</strong><p><a href="${site.social.instagram}">Instagram</a><br><a href="${site.social.facebook}">Facebook</a>${site.social.youtube?`<br><a href="${site.social.youtube}">YouTube</a>`:""}</p></div></div><div class="container legal">Educational information for qualified healthcare professionals. Individual clinical outcomes vary.</div></footer>`;
const crumbs=(items)=>`<div class="crumbs container">${items.map((x,i)=>i===items.length-1?`<span>${esc(x[0])}</span>`:`<a href="${x[1]}">${esc(x[0])}</a><b>›</b>`).join("")}</div>`;
const page=(title,desc,body,rel="",schema=null)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${site.domain}/${rel}"><meta name="robots" content="index,follow"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${site.domain}/${rel}"><link rel="stylesheet" href="/assets/css/site.css">${schema?`<script type="application/ld+json">${JSON.stringify(schema)}</script>`:""}</head><body>${nav()}${body}${footer()}</body></html>`;
const write=(rel,html)=>{const d=path.join(DIST,rel);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,"index.html"),html)};

const home=`<main>
<section class="hero-light"><div class="container hero-grid"><div><div class="eyebrow">Zhu’s Scalp Acupuncture · International Education</div><h1>Clinical heritage.<br>Systematic education.<br><em>Hope through function.</em></h1><p class="lead">International professional education in Zhu’s Scalp Acupuncture led by Dr. Ru Shan Shy and Dr. Sheng Chun Chang, grounded in the clinical legacy of Professor Ming Qing Zhu.</p><div class="actions"><a class="btn primary" href="/lineage/">Explore the Lineage</a><a class="btn" href="/education/">Professional Education</a></div></div><div class="hero-image-wrap"><img src="/assets/images/faculty/zhu-shy-chang-formal.jpg" alt="Professor Ming Qing Zhu with Dr. Ru Shan Shy and Dr. Sheng Chun Chang"><div class="caption"><strong>Professor Ming Qing Zhu</strong><span>with Dr. Ru Shan Shy & Dr. Sheng Chun Chang</span></div></div></div></section>
<section class="section cream"><div class="container intro-center"><div class="eyebrow">A documented clinical lineage</div><h2>From Professor Ming Qing Zhu to a new generation of international ZSA education.</h2><p class="lead">The relationship presented here is supported by historical photographs, direct clinical learning, formal transmission, teaching records and continuing professional education.</p></div></section>
<section class="section"><div class="container"><div class="eyebrow">How ZSA is taught</div><h2>Clinical reasoning before memorization.</h2><div class="grid g4"><div class="feature"><span>01</span><h3>Assess</h3><p>Define the functional problem and a meaningful clinical target.</p></div><div class="feature"><span>02</span><h3>Treat</h3><p>Select treatment zones and technique within a coherent strategy.</p></div><div class="feature"><span>03</span><h3>Reassess</h3><p>Observe functional response during the clinical encounter.</p></div><div class="feature"><span>04</span><h3>Integrate</h3><p>Use Dao Yin and active participation where clinically appropriate.</p></div></div></div></section>
<section class="section sage"><div class="container grid g2"><div><div class="eyebrow">Faculty</div><h2>Two educators. One clinical lineage.</h2><p class="lead">Dr. Ru Shan Shy and Dr. Sheng Chun Chang teach ZSA through systematic clinical reasoning, case-based learning and international professional exchange.</p><a class="btn primary" href="/faculty/">Meet the Faculty</a></div><div class="quote-card"><p>“Preserve the lineage. Clarify the system. Teach through clinical function.”</p><small>ZSA International Education</small></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Global Education</div><h2>Professional learning across regions.</h2><div class="grid g2">${regions.map(r=>`<article class="region"><img src="${r.image}" alt="${esc(r.name)} ZSA education"><div><small>${esc(r.status)}</small><h3>${esc(r.name)}</h3><p>${esc(r.summary)}</p><a href="/global-education/${r.slug}/">Explore region →</a></div></article>`).join("")}</div></div></section>
<section class="section cream"><div class="container grid g2"><div><div class="eyebrow">Knowledge Hub</div><h2>Build a searchable clinical education library.</h2><p class="lead">Structured articles, FAQs and future YouTube transcripts make the site easier for clinicians, Google and AI systems to understand.</p></div><div><a class="btn primary" href="/knowledge/">Enter Knowledge Hub</a><a class="btn" href="/faq/">ZSA FAQ</a></div></div></section>
</main>`;
write("",page(`${site.siteName} | Zhu’s Scalp Acupuncture`,"International professional education in Zhu’s Scalp Acupuncture, clinical heritage, systematic teaching and global training.",home,"",{"@context":"https://schema.org","@type":"EducationalOrganization","name":site.siteName,"url":site.domain,"sameAs":[site.social.instagram,site.social.facebook].filter(Boolean)}));

write("about-zsa",page("What is Zhu’s Scalp Acupuncture? | ZSA International Education","A structured introduction to Zhu’s Scalp Acupuncture, clinical assessment, treatment strategy, reassessment and Dao Yin.",`<main>${crumbs([["Home","/"],["About ZSA"]])}<section class="page-hero"><div class="container"><div class="eyebrow">About ZSA</div><h1>A clinical system, not a collection of scalp points.</h1><p class="lead">Zhu’s Scalp Acupuncture is presented on this educational platform as a structured clinical approach developed by Professor Ming Qing Zhu.</p></div></section><section class="section"><div class="container grid g2"><div><h2>Assessment → treatment → reassessment.</h2><p class="lead">Teaching begins with the patient’s functional presentation and a clearly defined clinical question. Treatment zones and technique are then selected within a broader strategy, followed by immediate reassessment.</p></div><div class="note">This website separates historical documentation, educational interpretation and clinical observation. Individual cases are not presented as guarantees of outcome.</div></div></section><section class="section cream"><div class="container"><div class="grid g4"><div class="feature"><span>01</span><h3>Clinical assessment</h3></div><div class="feature"><span>02</span><h3>Treatment strategy</h3></div><div class="feature"><span>03</span><h3>Functional reassessment</h3></div><div class="feature"><span>04</span><h3>Dao Yin</h3></div></div></div></section></main>`,"about-zsa/"));

write("professor-ming-qing-zhu",page(`${zhu.name} | Founder of Zhu’s Scalp Acupuncture`,zhu.summary,`<main>${crumbs([["Home","/"],["Lineage","/lineage/"],[zhu.name]])}<section class="page-hero"><div class="container grid g2"><div><div class="eyebrow">Founder · Zhu’s Scalp Acupuncture</div><h1>${esc(zhu.name)}</h1><p class="lead">${esc(zhu.summary)}</p></div><img class="portrait-wide" src="${zhu.image}" alt="${esc(zhu.name)} with ZSA faculty"></div></section><section class="section"><div class="container grid g2"><div><h2>Clinical legacy and educational transmission.</h2><p class="lead">This website uses historical records to document the lineage connecting Professor Zhu with Dr. Ru Shan Shy and Dr. Sheng Chun Chang.</p><a class="btn primary" href="/lineage/">View Heritage & Lineage</a></div><div class="note">${esc(zhu.note)}</div></div></section></main>`,"professor-ming-qing-zhu/",{"@context":"https://schema.org","@type":"Person","name":zhu.name,"description":zhu.role,"url":`${site.domain}/professor-ming-qing-zhu/`}));

write("lineage",page("ZSA Heritage & Lineage | ZSA International Education","Documented clinical heritage and educational transmission in Zhu’s Scalp Acupuncture.",`<main>${crumbs([["Home","/"],["Lineage"]])}<section class="page-hero"><div class="container"><div class="eyebrow">Heritage & Lineage</div><h1>Clinical heritage documented through learning, practice and teaching.</h1><p class="lead">A visual archive of clinical learning, formal transmission, professional teaching and international academic exchange.</p><a class="textlink" href="/professor-ming-qing-zhu/">Professor Ming Qing Zhu →</a></div></section><section class="section"><div class="container"><div class="timeline-grid">${history.map(h=>`<article class="timeline-card"><img src="${h.image}" alt="${esc(h.title)}"><small>${esc(h.category)} · ${esc(h.year)}</small><h3>${esc(h.title)}</h3><p>${esc(h.caption)}</p></article>`).join("")}</div></div></section></main>`,"lineage/"));

write("faculty",page("Faculty | ZSA International Education","Dr. Ru Shan Shy and Dr. Sheng Chun Chang, international educators in Zhu’s Scalp Acupuncture.",`<main>${crumbs([["Home","/"],["Faculty"]])}<section class="page-hero"><div class="container"><div class="eyebrow">Faculty</div><h1>Dr. Ru Shan Shy & Dr. Sheng Chun Chang</h1><p class="lead">Clinical educators continuing the transmission of Zhu’s Scalp Acupuncture through systematic teaching and international professional education.</p></div></section><section class="section"><div class="container grid g2">${faculty.map(f=>`<article class="faculty-card"><div class="faculty-placeholder"><span>Official portrait<br>from ZSATW archive</span></div><div><h2>${esc(f.name)}</h2><p>${esc(f.headline)}</p><a class="btn primary" href="/faculty/${f.slug}/">View profile</a></div></article>`).join("")}</div></section></main>`,"faculty/"));

for(const f of faculty){
const tags=f.focus.map(x=>`<span class="tag">${esc(x)}</span>`).join("");
const rows=f.timeline.map(t=>`<div class="profile-row"><small>${esc(t.label)}</small><p>${esc(t.text)}</p></div>`).join("");
write(`faculty/${f.slug}`,page(`${f.name} | ZSA International Education`,f.headline,`<main>${crumbs([["Home","/"],["Faculty","/faculty/"],[f.name]])}<section class="page-hero"><div class="container"><div class="eyebrow">Faculty Profile</div><h1>${esc(f.name)}</h1><p class="lead">${esc(f.summary)}</p><div class="tag-row">${tags}</div></div></section><section class="section"><div class="container grid g2"><div><h2>Biography</h2><p class="lead">${esc(f.bio)}</p></div><div class="faculty-placeholder large"><span>Official individual portrait<br>will replace this panel</span></div></div></section><section class="section cream"><div class="container"><h2>Professional profile</h2><div class="profile-table">${rows}</div></div></section></main>`,`faculty/${f.slug}/`,{"@context":"https://schema.org","@type":"Person","name":f.name,"url":`${site.domain}/faculty/${f.slug}/`,"affiliation":{"@type":"EducationalOrganization","name":site.siteName}}));
}

write("education",page("Professional ZSA Education | ZSA International Education","Systematic professional education in Zhu’s Scalp Acupuncture.",`<main>${crumbs([["Home","/"],["Education"]])}<section class="page-hero"><div class="container"><div class="eyebrow">Professional Education</div><h1>From foundations to clinical integration.</h1><p class="lead">A progressive educational framework built around clinical reasoning, technique, functional reassessment and Dao Yin.</p></div></section><section class="section"><div class="container grid g3"><div class="feature"><span>01</span><h3>Foundation</h3><p>Core framework, safety, assessment and treatment strategy.</p></div><div class="feature"><span>02</span><h3>Advanced</h3><p>Complex presentations and refinement of clinical strategy.</p></div><div class="feature"><span>03</span><h3>Clinical Masterclass</h3><p>Case-led teaching, demonstrations and supervised reasoning.</p></div></div></section></main>`,"education/"));

write("clinical-heritage",page("Clinical Heritage | ZSA International Education","Practice-based clinical heritage and hospital learning in Zhu’s Scalp Acupuncture.",`<main>${crumbs([["Home","/"],["Clinical Heritage"]])}<section class="page-hero"><div class="container"><div class="eyebrow">Clinical Heritage</div><h1>Clinical learning at the bedside.</h1><p class="lead">Hospital-based observation, case discussion and supervised practice form part of the historical educational record.</p></div></section><section class="section"><div class="container"><div class="note">Patient-related material should only be published where consent and institutional requirements are satisfied.</div><div class="grid g3 topgap">${clinical.map(e=>`<article class="image-card"><img src="${e.image}" alt="${esc(e.title)}"><h3>${esc(e.title)}</h3><p>${esc(e.caption)}</p></article>`).join("")}</div></div></section></main>`,"clinical-heritage/"));

write("global-education",page("Global ZSA Education | ZSA International Education","International Zhu’s Scalp Acupuncture teaching and professional academic exchange.",`<main>${crumbs([["Home","/"],["Global Education"]])}<section class="page-hero"><div class="container"><div class="eyebrow">Global Education</div><h1>One clinical framework, taught internationally.</h1><p class="lead">A durable archive of professional courses, intensive training and academic exchange.</p></div></section><section class="section"><div class="container grid g2">${regions.map(r=>`<article class="region"><img src="${r.image}" alt="${esc(r.name)}"><div><small>${esc(r.status)}</small><h3>${esc(r.name)}</h3><p>${esc(r.summary)}</p><a href="/global-education/${r.slug}/">Explore region →</a></div></article>`).join("")}</div></section></main>`,"global-education/"));
for(const r of regions) write(`global-education/${r.slug}`,page(`${r.name} | ZSA Global Education`,r.headline,`<main>${crumbs([["Home","/"],["Global Education","/global-education/"],[r.name]])}<section class="page-hero"><div class="container"><div class="eyebrow">Global Education · ${esc(r.name)}</div><h1>${esc(r.headline)}</h1><p class="lead">${esc(r.summary)}</p></div></section><section class="section"><div class="container grid g2"><img class="portrait-wide" src="${r.image}" alt="${esc(r.name)} ZSA education"><div><h2>Regional focus</h2><ul class="clean-list">${r.highlights.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></div></section></main>`,`global-education/${r.slug}/`));

const faqSchema={"@context":"https://schema.org","@type":"FAQPage","mainEntity":knowledge.faq.map(x=>({"@type":"Question","name":x.q,"acceptedAnswer":{"@type":"Answer","text":x.a}}))};
write("faq",page("Zhu’s Scalp Acupuncture FAQ | ZSA International Education","Frequently asked questions about Zhu’s Scalp Acupuncture, its founder, faculty, clinical framework and international education.",`<main>${crumbs([["Home","/"],["FAQ"]])}<section class="page-hero"><div class="container"><div class="eyebrow">ZSA FAQ</div><h1>Clear answers about Zhu’s Scalp Acupuncture.</h1></div></section><section class="section"><div class="container faq">${knowledge.faq.map(x=>`<details><summary>${esc(x.q)}</summary><p>${esc(x.a)}</p></details>`).join("")}</div></section></main>`,"faq/",faqSchema));

write("knowledge",page("ZSA Knowledge Hub | Zhu’s Scalp Acupuncture Education","Searchable educational topics in Zhu’s Scalp Acupuncture for healthcare professionals.",`<main>${crumbs([["Home","/"],["Knowledge Hub"]])}<section class="page-hero"><div class="container"><div class="eyebrow">Knowledge Hub</div><h1>A structured library for clinical ZSA education.</h1><p class="lead">Articles are designed to connect clinical concepts, faculty teaching, future video transcripts and verified historical records.</p></div></section><section class="section"><div class="container grid g2">${knowledge.topics.map(t=>`<article class="knowledge-card"><small>Clinical Concept</small><h2>${esc(t.title)}</h2><p>${esc(t.summary)}</p><a href="/knowledge/${t.slug}/">Read topic →</a></article>`).join("")}</div></section><section class="section cream"><div class="container"><h2>Questions about ZSA?</h2><a class="btn primary" href="/faq/">Open ZSA FAQ</a></div></section></main>`,"knowledge/"));

for(const t of knowledge.topics) write(`knowledge/${t.slug}`,page(`${t.title} | ZSA Knowledge Hub`,t.summary,`<main>${crumbs([["Home","/"],["Knowledge Hub","/knowledge/"],[t.title]])}<article class="article"><div class="container narrow"><div class="eyebrow">ZSA Clinical Concept</div><h1>${esc(t.title)}</h1><p class="lead">${esc(t.summary)}</p><hr><h2>Educational scope</h2><p>This topic page establishes a searchable educational framework. Detailed clinical teaching, references, faculty commentary and related video material will be added from verified ZSA educational content.</p><div class="note">This material is intended for professional education and does not replace individualized medical assessment or clinical training.</div></div></article></main>`,`knowledge/${t.slug}/`,{"@context":"https://schema.org","@type":"Article","headline":t.title,"description":t.summary,"publisher":{"@type":"EducationalOrganization","name":site.siteName}}));

write("video-library",page("ZSA Video Knowledge Hub | ZSA International Education","YouTube-based clinical and teaching video library for Zhu’s Scalp Acupuncture.",`<main>${crumbs([["Home","/"],["Videos"]])}<section class="page-hero"><div class="container"><div class="eyebrow">Video Knowledge Hub</div><h1>YouTube for video. ZSATW.com for clinical context.</h1><p class="lead">Important lectures and cases will receive dedicated pages with learning points, transcript context and structured video metadata.</p></div></section><section class="section"><div class="container">${videos.map(v=>`<article class="knowledge-card"><h2>${esc(v.title)}</h2><p>${esc(v.summary)}</p></article>`).join("")}</div></section></main>`,"video-library/"));

write("contact",page("Contact | ZSA International Education","Contact ZSA International Education for professional education and collaboration.",`<main>${crumbs([["Home","/"],["Contact"]])}<section class="page-hero"><div class="container"><div class="eyebrow">Contact</div><h1>Education & professional collaboration.</h1></div></section><section class="section"><div class="container grid g2"><div class="knowledge-card"><h3>Official channels</h3><p><a href="${site.social.instagram}">Instagram</a><br><a href="${site.social.facebook}">Facebook</a>${site.social.youtube?`<br><a href="${site.social.youtube}">YouTube</a>`:""}</p></div><div class="knowledge-card"><h3>Email</h3><p>${esc(site.contactEmail)}</p></div></div></section></main>`,"contact/"));

fs.cpSync(path.join(ROOT,"public"),DIST,{recursive:true});
const urls=["","about-zsa/","professor-ming-qing-zhu/","lineage/","faculty/","faculty/ru-shan-shy/","faculty/sheng-chun-chang/","education/","clinical-heritage/","global-education/","global-education/australia/","global-education/asia/","global-education/europe/","global-education/north-america/","knowledge/","knowledge/clinical-assessment/","knowledge/treatment-strategy/","knowledge/dao-yin/","knowledge/clinical-reassessment/","faq/","video-library/","contact/"];
fs.writeFileSync(path.join(DIST,"robots.txt"),`User-agent: *\nAllow: /\n\nSitemap: ${site.domain}/sitemap.xml\n`);
fs.writeFileSync(path.join(DIST,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/sitemap/0.9">${urls.map(u=>`<url><loc>${site.domain}/${u}</loc></url>`).join("")}</urlset>`);
console.log(`Built ${urls.length} pages into dist/`);
